sudo: required

# Recommended addition from updates on Udemy course site
language: generic

# Tells travis that we need docker for our build
services:
    - docker

# container tag is only used inside Travis
before_install:
    - docker build -t cburkins/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true cburkins/docker-react npm run test -- --coverage
