sudo: required

# Recommended addition from updates on Udemy course site
language: generic

# Tells travis that we need docker for our build
services:
    - docker

# container tag is only used inside Travis
before_install:
    - docker build -t cburkins/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true cburkins/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: "udemy-docker-react"
    env: "UdemyDockerReact-env"
    # Automatically created as part of ElasticBeanstalk app, have to search in S3 for it
    bucket_name: elasticbeanstalk-us-east-1-745400479556
    # Bucket "folder" won't be created, but use same as "app" above
    bucket_path: "udemy-docker-react"
    # Only deploy when changes are pushed to "master" branch, not other branches
    on:
        branch: master

    # Be sure to give the AWS user the policy "AWSElasticBeanstalkFullAccess"
    # These variables are stores in the repo settings within Travis CI
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    # access_key_id: $AWS_ACCESS_KEY
    # secret_access_key:
    #     secure: "$AWS_SECRET_KEY"
